# Generated by Django 4.1 on 2022-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_is_finised_alter_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_finised',
            new_name='is_finished',
        ),
    ]
