# Generated by Django 4.1 on 2022-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchListtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('release_date', models.DateField()),
                ('review', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='MywatchlistItem',
        ),
    ]
